#include <windows.h>
#include <gl/gl.h>
#include <gdiplus.h>
#include "rev_platform.h"
#include "rev_shader.h"
#include "rev_xm.h"
#include "rev_runtime.h"
#include "rev_mesh.h"
#if defined(REV_GLTF_AVAILABLE)
#include "rev_gltf.h"
#endif
#include <cstdio>
#include <cstring>

// Pull shared types into the global scope for this file.
using rev::runtime::ColorRGB;
using rev::runtime::ImageCue;
using rev::runtime::ImageTexture;
using rev::runtime::TextCue;
using rev::runtime::TextTexture;
using rev::runtime::MusicCue;
using rev::runtime::ComputeEffectOpacity;
using rev::runtime::LoadImageTexture;
using rev::runtime::LoadImageTextureFromMemory;
using rev::runtime::RenderTextToTexture;
using rev::runtime::MeshCue;
using rev::runtime::LoadImageCue;
using rev::runtime::LoadTextCue;
using rev::runtime::LoadMusicCue;
using rev::runtime::LoadMeshCue;
using rev::runtime::LoadCurves;
using rev::runtime::Mat4Perspective;
using rev::runtime::Mat4LookAt;
using rev::runtime::Mat4Model;
using rev::runtime::Mat4Multiply;

// When built with -DHIMYM_PACKED_ASSETS, all asset data is embedded in the binary.
// packed_assets.h is generated by rev_pack into the cmake binary dir before building.
#ifdef HIMYM_PACKED_ASSETS
#include "rev_pack.h"
#include "packed_assets.h"
#endif

#pragma comment(lib, "gdiplus.lib")
#pragma comment(lib, "winmm.lib")
#include <mmsystem.h>

// Global debug log file
static FILE* g_logfile = nullptr;

// ===== WinMM audio thread for XM playback =====
static const int kAudioSampleRate = 48000;
static const int kAudioChannels   = 2;
static const int kAudioFrames     = 2048;   // frames per waveOut buffer
static const int kAudioBufCount   = 4;      // ring-buffer depth

struct AudioState {
    rev::xm::Player* player;
    HWAVEOUT         wave_out;
    WAVEHDR          headers[kAudioBufCount];
    int16_t*         pcm[kAudioBufCount];
    float            fbuf[kAudioFrames * kAudioChannels];
    volatile bool    stop;
};

static DWORD WINAPI AudioThreadProc(LPVOID param) {
    AudioState* a = (AudioState*)param;

    for (int i = 0; i < kAudioBufCount; ++i) {
        a->pcm[i] = new int16_t[kAudioFrames * kAudioChannels];
        memset(&a->headers[i], 0, sizeof(WAVEHDR));
        a->headers[i].lpData         = (LPSTR)a->pcm[i];
        a->headers[i].dwBufferLength = kAudioFrames * kAudioChannels * (DWORD)sizeof(int16_t);
        waveOutPrepareHeader(a->wave_out, &a->headers[i], sizeof(WAVEHDR));
    }

    // Pre-fill and submit all buffers before entering the loop
    for (int i = 0; i < kAudioBufCount; ++i) {
        rev::xm::Update(a->player, a->fbuf, kAudioFrames);
        for (int s = 0; s < kAudioFrames * kAudioChannels; ++s) {
            float v = a->fbuf[s];
            if (v >  1.0f) v =  1.0f;
            if (v < -1.0f) v = -1.0f;
            a->pcm[i][s] = (int16_t)(v * 32767.0f);
        }
        waveOutWrite(a->wave_out, &a->headers[i], sizeof(WAVEHDR));
    }

    while (!a->stop) {
        for (int i = 0; i < kAudioBufCount; ++i) {
            if (a->headers[i].dwFlags & WHDR_DONE) {
                a->headers[i].dwFlags &= ~WHDR_DONE;
                rev::xm::Update(a->player, a->fbuf, kAudioFrames);
                for (int s = 0; s < kAudioFrames * kAudioChannels; ++s) {
                    float v = a->fbuf[s];
                    if (v >  1.0f) v =  1.0f;
                    if (v < -1.0f) v = -1.0f;
                    a->pcm[i][s] = (int16_t)(v * 32767.0f);
                }
                waveOutWrite(a->wave_out, &a->headers[i], sizeof(WAVEHDR));
            }
        }
        Sleep(1);
    }

    waveOutReset(a->wave_out);
    for (int i = 0; i < kAudioBufCount; ++i) {
        waveOutUnprepareHeader(a->wave_out, &a->headers[i], sizeof(WAVEHDR));
        delete[] a->pcm[i];
    }
    return 0;
}

// Define missing GL constants
#ifndef GL_COLOR_BUFFER_BIT
#define GL_COLOR_BUFFER_BIT 0x00004000
#endif
#ifndef GL_TRIANGLE_STRIP
#define GL_TRIANGLE_STRIP 0x0005
#endif
#ifndef GL_CLAMP
#define GL_CLAMP 0x2900
#endif
#ifndef GL_TEXTURE0
#define GL_TEXTURE0 0x84C0
#endif

// GL 3.3 function pointers (VAO support required for core profile)
typedef void (APIENTRY *PFNGLGENVERTEXARRAYSPROC)(GLsizei n, GLuint* arrays);
typedef void (APIENTRY *PFNGLBINDVERTEXARRAYPROC)(GLuint array);
typedef void (APIENTRY *PFNGLACTIVETEXTUREPROC)(GLenum texture);

static PFNGLGENVERTEXARRAYSPROC glGenVertexArrays = nullptr;
static PFNGLBINDVERTEXARRAYPROC glBindVertexArray = nullptr;
static PFNGLACTIVETEXTUREPROC glActiveTexture = nullptr;

// Shader cue data structure (runtime-local; editor uses its own ShaderCue with more fields)
struct ShaderCue {
    int shader_scene_id;
    float palette_low[3];
    float palette_mid[3];
    float palette_high[3];
    float speed;
    float intensity;
    float warp;
    float exposure_base;
    float exposure_ramp;
    float fade_base;
    float fade_ramp;
    float cue_start;
    float cue_end;
    float fade_in;
    float fade_out;
    int layer_role;
    float opacity;
    int blend_mode;
    int layer_order;
    
    // Curve assignments (-1 = no curve)
    int curve_speed;
    int curve_intensity;
    int curve_warp;
    int curve_exposure;
    int curve_fade;
    int curve_palette_low_r;
    int curve_palette_low_g;
    int curve_palette_low_b;
    int curve_palette_mid_r;
    int curve_palette_mid_g;
    int curve_palette_mid_b;
    int curve_palette_high_r;
    int curve_palette_high_g;
    int curve_palette_high_b;
    int curve_opacity;
    int curve_exposure_ramp;
    int curve_fade_ramp;
};

// Music cue data structure — provided by rev_runtime (MusicCue using above)
// Image cue data structure — provided by rev_runtime (ImageCue using above)

// Image texture data — provided by rev_runtime (ImageTexture using above)

// Text cue data structure — provided by rev_runtime (TextCue using above)
// Text texture — provided by rev_runtime (TextTexture using above)

// Parse cues.txt and extract first shader cue
bool LoadShaderCue(const char* path, ShaderCue* cue) {
    FILE* f = nullptr;
    fopen_s(&f, path, "r");
    if (!f) return false;
    
    char line[512];
    bool in_shader_cues = false;
    bool found = false;
    
    while (fgets(line, sizeof(line), f)) {
        // Trim whitespace
        char* start = line;
        while (*start == ' ' || *start == '\t' || *start == '\n' || *start == '\r') start++;
        
        if (strstr(start, "[shader_cues]")) {
            in_shader_cues = true;
            continue;
        }
        
        if (start[0] == '[' && in_shader_cues) {
            break;  // End of shader_cues section
        }
        
        if (in_shader_cues && start[0] != '#' && start[0] != '\0' && start[0] != '\n') {
            // Parse shader cue line - full 38-field format with backwards compatibility
            // Format: shader_scene_id|palette(9)|speed|intensity|warp|exposure_base|exposure_ramp|fade_base|fade_ramp|
            //         cue_start|cue_end|fade_in|fade_out|layer_role|opacity|blend_mode|layer_order|
            //         curve fields (13)
            
            // Initialize curve fields to -1 (no curve)
            cue->curve_speed = cue->curve_intensity = cue->curve_warp = -1;
            cue->curve_exposure = cue->curve_fade = -1;
            cue->curve_palette_low_r = cue->curve_palette_low_g = cue->curve_palette_low_b = -1;
            cue->curve_palette_mid_r = cue->curve_palette_mid_g = cue->curve_palette_mid_b = -1;
            cue->curve_palette_high_r = cue->curve_palette_high_g = cue->curve_palette_high_b = -1;
            cue->curve_opacity = cue->curve_exposure_ramp = cue->curve_fade_ramp = -1;
            
            int parsed = sscanf_s(start,
                "%d|%f|%f|%f|%f|%f|%f|%f|%f|%f|%f|%f|%f|%f|%f|%f|%f|%f|%f|%f|%f|%d|%f|%d|%d|%d|%d|%d|%d|%d|%d|%d|%d|%d|%d|%d|%d|%d|%d|%d|%d|%d",
                &cue->shader_scene_id,
                &cue->palette_low[0], &cue->palette_low[1], &cue->palette_low[2],
                &cue->palette_mid[0], &cue->palette_mid[1], &cue->palette_mid[2],
                &cue->palette_high[0], &cue->palette_high[1], &cue->palette_high[2],
                &cue->speed, &cue->intensity, &cue->warp,
                &cue->exposure_base, &cue->exposure_ramp,
                &cue->fade_base, &cue->fade_ramp,
                &cue->cue_start, &cue->cue_end,
                &cue->fade_in, &cue->fade_out,
                &cue->layer_role, &cue->opacity, &cue->blend_mode, &cue->layer_order,
                &cue->curve_speed, &cue->curve_intensity, &cue->curve_warp,
                &cue->curve_exposure, &cue->curve_fade,
                &cue->curve_palette_low_r, &cue->curve_palette_low_g, &cue->curve_palette_low_b,
                &cue->curve_palette_mid_r, &cue->curve_palette_mid_g, &cue->curve_palette_mid_b,
                &cue->curve_palette_high_r, &cue->curve_palette_high_g, &cue->curve_palette_high_b,
                &cue->curve_opacity, &cue->curve_exposure_ramp, &cue->curve_fade_ramp);
            
            if (parsed >= 14) {  // At least old format (14 basic fields)
                found = true;
                break;
            }
        }
    }
    
    fclose(f);
    return found;
}

// LoadMusicCue, LoadImageCue, LoadTextCue, LoadImageTexture,
// LoadImageTextureFromMemory, RenderTextToTexture, and ComputeEffectOpacity
// are all provided by rev_runtime (via the using declarations at the top).

// Minimal vertex shader - fullscreen quad
const char* vertex_shader = R"(
#version 330 core
out vec2 uv;
void main() {
    float x = -1.0 + float((gl_VertexID & 1) << 2);
    float y = -1.0 + float((gl_VertexID & 2) << 1);
    uv = vec2((x + 1.0) * 0.5, (y + 1.0) * 0.5);
    gl_Position = vec4(x, y, 0.0, 1.0);
}
)";
// Sprite vertex shader - textured quad with position/scale
const char* sprite_vertex_shader = R"(
#version 330 core
out vec2 uv;
uniform vec2 u_position;  // -1 to 1
uniform vec2 u_size;      // width, height in normalized coords
void main() {
    float x = -1.0 + float((gl_VertexID & 1) << 2);
    float y = -1.0 + float((gl_VertexID & 2) << 1);
    uv = vec2((x + 1.0) * 0.5, 1.0 - (y + 1.0) * 0.5);  // Flip V coordinate
    gl_Position = vec4(u_position.x + x * u_size.x, u_position.y + y * u_size.y, 0.0, 1.0);
}
)";

// Sprite fragment shader - textured with opacity
const char* sprite_fragment_shader = R"(
#version 330 core
in vec2 uv;
out vec4 fragColor;
uniform sampler2D u_texture;
uniform float u_opacity;
void main() {
    vec4 texColor = texture(u_texture, uv);
    fragColor = vec4(texColor.rgb, texColor.a * u_opacity);
}
)";
// Mesh (3D Phong) shaders
const char* mesh_vertex_shader_src = R"(
#version 330 core
layout(location = 0) in vec3 a_pos;
layout(location = 1) in vec3 a_normal;
layout(location = 2) in vec2 a_uv;
out vec3 v_frag_pos;
out vec3 v_normal;
out vec2 v_uv;
uniform mat4 u_model;
uniform mat4 u_view;
uniform mat4 u_projection;
void main() {
    vec4 world_pos = u_model * vec4(a_pos, 1.0);
    v_frag_pos = world_pos.xyz;
    v_normal   = mat3(transpose(inverse(u_model))) * a_normal;
    v_uv       = a_uv;
    gl_Position = u_projection * u_view * world_pos;
}
)";

const char* mesh_fragment_shader_src = R"(
#version 330 core
in vec3 v_frag_pos;
in vec3 v_normal;
in vec2 v_uv;
out vec4 fragColor;
uniform vec3  u_light_pos;
uniform vec3  u_view_pos;
uniform vec4  u_color;
uniform float u_metallic;
uniform float u_roughness;
uniform sampler2D u_base_color_texture;
uniform int u_has_texture;
void main() {
    vec3  base = u_color.rgb;
    if (u_has_texture != 0) {
        vec4 tex_color = texture(u_base_color_texture, v_uv);
        base *= tex_color.rgb;
    }
    vec3  norm     = normalize(v_normal);
    vec3  ldir     = normalize(u_light_pos - v_frag_pos);
    vec3  vdir     = normalize(u_view_pos  - v_frag_pos);
    vec3  hdir     = normalize(ldir + vdir);
    float ambient  = 0.15;
    float diff     = max(dot(norm, ldir), 0.0) * (1.0 - u_metallic * 0.9);
    float shininess   = mix(2.0, 256.0, 1.0 - u_roughness);
    float spec_fac    = pow(max(dot(norm, hdir), 0.0), shininess);
    vec3  spec_col    = mix(vec3(0.04), base, u_metallic);
    vec3  spec        = spec_col * spec_fac * (1.0 - u_roughness * 0.85);
    vec3  result      = base * (ambient + diff) + spec;
    fragColor = vec4(result, u_color.a);
}
)";

// Fragment shaders - 10 presets
const char* fragment_shaders[] = {
    // 0: Plasma Vibrant
    R"(
#version 330 core
in vec2 uv;
out vec4 fragColor;
uniform float u_time;
uniform vec2 u_resolution;
uniform vec3 u_palette_low;
uniform vec3 u_palette_mid;
uniform vec3 u_palette_high;
uniform float u_speed;
uniform float u_intensity;

void main() {
    vec2 p = (uv * 2.0 - 1.0) * vec2(u_resolution.x / u_resolution.y, 1.0);
    float t = u_time * u_speed;
    
    float v = sin(p.x * 10.0 + t) + sin(p.y * 10.0 + t * 0.5) + sin((p.x + p.y) * 5.0 + t * 0.8);
    v = v / 3.0 * u_intensity;
    
    vec3 col = mix(mix(u_palette_low, u_palette_mid, smoothstep(-1.0, 0.0, v)), 
                   u_palette_high, smoothstep(0.0, 1.0, v));
    
    fragColor = vec4(col, 1.0);
}
)",
    
    // 1: Tunnel Neon
    R"(
#version 330 core
in vec2 uv;
out vec4 fragColor;
uniform float u_time;
uniform vec2 u_resolution;
uniform vec3 u_palette_low;
uniform vec3 u_palette_mid;
uniform vec3 u_palette_high;
uniform float u_speed;

void main() {
    vec2 p = (uv * 2.0 - 1.0) * vec2(u_resolution.x / u_resolution.y, 1.0);
    float t = u_time * u_speed;
    
    float r = length(p);
    float a = atan(p.y, p.x);
    float d = 1.0 / (r + 0.1);
    
    float tunnel = fract(d - t * 0.5);
    float rings = abs(sin(tunnel * 20.0));
    
    vec3 col = mix(u_palette_low, u_palette_high, rings);
    col = mix(col, u_palette_mid, smoothstep(0.3, 0.7, tunnel));
    
    fragColor = vec4(col, 1.0);
}
)",
    
    // 2: Raymarcher SDF
    R"(
#version 330 core
in vec2 uv;
out vec4 fragColor;
uniform float u_time;
uniform vec2 u_resolution;
uniform vec3 u_palette_low;
uniform vec3 u_palette_high;
uniform float u_speed;

float sdSphere(vec3 p, float r) { return length(p) - r; }

void main() {
    vec2 p = (uv * 2.0 - 1.0) * vec2(u_resolution.x / u_resolution.y, 1.0);
    float t = u_time * u_speed;
    
    vec3 ro = vec3(0, 0, -3);
    vec3 rd = normalize(vec3(p, 1.0));
    
    float dist = 0.0;
    for (int i = 0; i < 32; i++) {
        vec3 pos = ro + rd * dist;
        float d = sdSphere(pos - vec3(sin(t) * 0.5, cos(t * 0.7) * 0.5, 0), 0.5);
        if (d < 0.001) break;
        dist += d;
    }
    
    vec3 col = mix(u_palette_low, u_palette_high, smoothstep(2.0, 5.0, dist));
    fragColor = vec4(col, 1.0);
}
)",
    
    // 3: Fractal Mandelbrot
    R"(
#version 330 core
in vec2 uv;
out vec4 fragColor;
uniform float u_time;
uniform vec2 u_resolution;
uniform vec3 u_palette_low;
uniform vec3 u_palette_mid;
uniform vec3 u_palette_high;
uniform float u_speed;

void main() {
    vec2 p = (uv * 2.0 - 1.0) * vec2(u_resolution.x / u_resolution.y, 1.0) * 2.0;
    float t = u_time * u_speed * 0.2;
    p += vec2(sin(t) * 0.3, cos(t * 0.7) * 0.3);
    
    vec2 c = p;
    vec2 z = vec2(0.0);
    float iter = 0.0;
    
    for (int i = 0; i < 64; i++) {
        z = vec2(z.x * z.x - z.y * z.y, 2.0 * z.x * z.y) + c;
        if (length(z) > 4.0) break;
        iter += 1.0;
    }
    
    float v = iter / 64.0;
    vec3 col = mix(mix(u_palette_low, u_palette_mid, v), u_palette_high, smoothstep(0.7, 1.0, v));
    
    fragColor = vec4(col, 1.0);
}
)",
    
    // 4: Voronoi Cells
    R"(
#version 330 core
in vec2 uv;
out vec4 fragColor;
uniform float u_time;
uniform vec2 u_resolution;
uniform vec3 u_palette_low;
uniform vec3 u_palette_mid;
uniform vec3 u_palette_high;
uniform float u_speed;

vec2 hash2(vec2 p) {
    p = vec2(dot(p, vec2(127.1, 311.7)), dot(p, vec2(269.5, 183.3)));
    return fract(sin(p) * 43758.5453);
}

void main() {
    vec2 p = uv * 8.0 * vec2(u_resolution.x / u_resolution.y, 1.0);
    float t = u_time * u_speed;
    
    vec2 ip = floor(p);
    vec2 fp = fract(p);
    
    float minDist = 1.0;
    for (int y = -1; y <= 1; y++) {
        for (int x = -1; x <= 1; x++) {
            vec2 offset = vec2(x, y);
            vec2 h = hash2(ip + offset);
            vec2 pt = offset + sin(h * 6.28 + t) * 0.5 + 0.5;
            float d = length(pt - fp);
            minDist = min(minDist, d);
        }
    }
    
    vec3 col = mix(mix(u_palette_low, u_palette_mid, minDist), u_palette_high, smoothstep(0.5, 1.0, minDist));
    
    fragColor = vec4(col, 1.0);
}
)",
    
    // 5: Wave Distortion
    R"(
#version 330 core
in vec2 uv;
out vec4 fragColor;
uniform float u_time;
uniform vec2 u_resolution;
uniform vec3 u_palette_low;
uniform vec3 u_palette_high;
uniform float u_speed;
uniform float u_warp;

void main() {
    vec2 p = (uv * 2.0 - 1.0) * vec2(u_resolution.x / u_resolution.y, 1.0);
    float t = u_time * u_speed;
    
    p.x += sin(p.y * 5.0 + t) * u_warp;
    p.y += cos(p.x * 5.0 + t * 0.7) * u_warp;
    
    float d = length(p);
    float wave = sin(d * 10.0 - t * 2.0) * 0.5 + 0.5;
    
    vec3 col = mix(u_palette_low, u_palette_high, wave);
    
    fragColor = vec4(col, 1.0);
}
)",
    
    // 6: Particle System
    R"(
#version 330 core
in vec2 uv;
out vec4 fragColor;
uniform float u_time;
uniform vec2 u_resolution;
uniform vec3 u_palette_low;
uniform vec3 u_palette_mid;
uniform vec3 u_palette_high;
uniform float u_speed;

float hash(vec2 p) {
    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

void main() {
    vec2 p = (uv * 2.0 - 1.0) * vec2(u_resolution.x / u_resolution.y, 1.0);
    float t = u_time * u_speed;
    
    vec3 col = vec3(0.0);
    
    for (int i = 0; i < 32; i++) {
        float fi = float(i);
        float h = hash(vec2(fi, fi * 0.5));
        float angle = h * 6.28;
        float radius = fract(h * 7.13 + t * 0.3) * 2.0;
        
        vec2 pos = vec2(cos(angle), sin(angle)) * radius;
        float d = length(p - pos);
        float particle = smoothstep(0.05, 0.0, d);
        
        vec3 pcol = mix(u_palette_low, mix(u_palette_mid, u_palette_high, h), fract(radius));
        col += pcol * particle;
    }
    
    fragColor = vec4(col, 1.0);
}
)",
    
    // 7: Starfield
    R"(
#version 330 core
in vec2 uv;
out vec4 fragColor;
uniform float u_time;
uniform vec2 u_resolution;
uniform vec3 u_palette_high;
uniform float u_speed;

float hash(vec3 p) {
    return fract(sin(dot(p, vec3(127.1, 311.7, 74.7))) * 43758.5453);
}

void main() {
    vec2 p = (uv * 2.0 - 1.0) * vec2(u_resolution.x / u_resolution.y, 1.0);
    float t = u_time * u_speed;
    
    vec3 rd = normalize(vec3(p, 1.0));
    vec3 col = vec3(0.0);
    
    for (int i = 0; i < 64; i++) {
        float fi = float(i);
        vec3 star_pos = vec3(hash(vec3(fi, fi * 0.1, 0)) * 2.0 - 1.0,
                             hash(vec3(fi * 0.5, fi, 0)) * 2.0 - 1.0,
                             hash(vec3(fi, 0, fi * 0.7)) * 5.0 + 1.0);
        
        star_pos.z = fract(star_pos.z - t * 0.5) * 10.0;
        vec3 proj = star_pos / star_pos.z;
        
        float d = length(proj.xy - p);
        float star = smoothstep(0.02, 0.0, d) / star_pos.z;
        col += u_palette_high * star;
    }
    
    fragColor = vec4(col, 1.0);
}
)",
    
    // 8: Glow Orbs
    R"(
#version 330 core
in vec2 uv;
out vec4 fragColor;
uniform float u_time;
uniform vec2 u_resolution;
uniform vec3 u_palette_low;
uniform vec3 u_palette_mid;
uniform vec3 u_palette_high;
uniform float u_speed;

void main() {
    vec2 p = (uv * 2.0 - 1.0) * vec2(u_resolution.x / u_resolution.y, 1.0);
    float t = u_time * u_speed;
    
    vec3 col = vec3(0.0);
    
    for (int i = 0; i < 5; i++) {
        float fi = float(i);
        vec2 orb_pos = vec2(sin(t * 0.5 + fi * 1.2) * 0.6, cos(t * 0.7 + fi * 0.8) * 0.6);
        float d = length(p - orb_pos);
        float glow = 0.02 / d;
        
        vec3 orb_col = mix(mix(u_palette_low, u_palette_mid, fi / 5.0), u_palette_high, smoothstep(0.3, 0.8, fi / 5.0));
        col += orb_col * glow;
    }
    
    fragColor = vec4(col, 1.0);
}
)",
    
    // 9: Matrix Rain
    R"(
#version 330 core
in vec2 uv;
out vec4 fragColor;
uniform float u_time;
uniform vec2 u_resolution;
uniform vec3 u_palette_high;
uniform float u_speed;

float hash(vec2 p) {
    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

void main() {
    vec2 p = uv * vec2(40.0, 30.0);
    vec2 ip = floor(p);
    vec2 fp = fract(p);
    float t = u_time * u_speed;
    
    float h = hash(ip);
    float drop = fract(h * 7.13 - t * 0.5);
    
    float char_y = fract((ip.y + drop * 30.0) / 30.0);
    float char_brightness = smoothstep(0.0, 0.05, drop) * smoothstep(1.0, 0.8, drop);
    
    float char = step(0.3, hash(ip + floor(t * 10.0)));
    float glyph = char * char_brightness;
    
    vec3 col = u_palette_high * glyph;
    
    fragColor = vec4(col, 1.0);
}
)"
};

int main(int argc, char* argv[]) {
    // Normalise CWD to workspace root regardless of launch location.
    // The exe lives at build/bin/Release/ — walk up 3 levels.
    {
        char exe_path[MAX_PATH] = {};
        GetModuleFileNameA(NULL, exe_path, sizeof(exe_path));
        char* p = strrchr(exe_path, '\\');
        if (p) *p = '\0';
        for (int i = 0; i < 3; ++i) {
            p = strrchr(exe_path, '\\');
            if (p) *p = '\0';
        }
        if (exe_path[0]) SetCurrentDirectoryA(exe_path);
    }

    // Allocate console for debug output
    AllocConsole();
    FILE* fp;
    freopen_s(&fp, "CONOUT$", "w", stdout);
    freopen_s(&fp, "CONOUT$", "w", stderr);

    // Also log to file for debugging
    fopen_s(&g_logfile, "intro_debug.log", "w");

    printf("=== HiMYM Minimal Intro ===\n\n");
    if (g_logfile) fprintf(g_logfile, "=== HiMYM Minimal Intro Debug Log ===\n\n");

    // Cues file path: argv[1] takes priority (editor always passes it).
    // Packed standalone build: extract embedded kPackedCuesContent to a temp file —
    // zero disk dependency, works from any launch location.
#ifdef HIMYM_PACKED_ASSETS
    char packed_cues_tmp[MAX_PATH] = {};
#ifdef HIMYM_HAS_PACKED_CUES
    {
        char tmpdir[MAX_PATH] = {};
        GetTempPathA(sizeof(tmpdir), tmpdir);
        GetTempFileNameA(tmpdir, "cues", 0, packed_cues_tmp);
        FILE* tf = nullptr;
        fopen_s(&tf, packed_cues_tmp, "wb");
        if (tf) { fwrite(kPackedCuesContent, 1, kPackedCuesSize, tf); fclose(tf); }
        if (g_logfile) {
            fprintf(g_logfile, "[Packed] Wrote embedded cues (%zu bytes) to: %s\n",
                    kPackedCuesSize, packed_cues_tmp);
            fflush(g_logfile);
        }
    }
#endif
    const char* cues_path = (argc > 1 && argv[1] && argv[1][0]) ? argv[1]
                          : (packed_cues_tmp[0] ? packed_cues_tmp : "assets/cues.txt");
#else
    const char* cues_path = (argc > 1 && argv[1] && argv[1][0]) ? argv[1] : "assets/cues.txt";
#endif
    printf("Cues file: %s\n", cues_path);
    if (g_logfile) fprintf(g_logfile, "Cues file: %s\n", cues_path);

    // Load shader cue
    ShaderCue cue = {};
    if (!LoadShaderCue(cues_path, &cue)) {
        // Default fallback
        cue.shader_scene_id = 0;
        cue.palette_low[0] = 0.1f; cue.palette_low[1] = 0.3f; cue.palette_low[2] = 0.8f;
        cue.palette_mid[0] = 0.45f; cue.palette_mid[1] = 0.25f; cue.palette_mid[2] = 0.7f;
        cue.palette_high[0] = 0.8f; cue.palette_high[1] = 0.2f; cue.palette_high[2] = 0.6f;
        cue.speed = 1.0f;
        cue.intensity = 1.0f;
        cue.warp = 0.5f;
        cue.exposure_base = 0.76f;
    }
    
    // Load curves
    rev::curve::Curve curves[32];
    int curve_count = LoadCurves(cues_path, curves, 32);
    printf("Loaded %d curves\n", curve_count);
    if (g_logfile) {
        fprintf(g_logfile, "Loaded %d curves\n", curve_count);
        for (int i = 0; i < curve_count; ++i) {
            fprintf(g_logfile, "  Curve %d: duration=%.2f, points=%d, wrap_mode=%d\n", 
                i, curves[i].duration, curves[i].point_count, (int)curves[i].wrap_mode);
        }
    }
    
    // Load music cue
    MusicCue music_cue = {};
    bool has_music = LoadMusicCue(cues_path, &music_cue);
    
    // Load image cue
    ImageCue image_cue = {};
    bool has_image = LoadImageCue(cues_path, &image_cue);
    ImageTexture image_tex = {};
    bool image_loaded = false;
    
    printf("Image cue loaded: %s\n", has_image ? "YES" : "NO");
    if (g_logfile) {
        fprintf(g_logfile, "Image cue loaded: %s\n", has_image ? "YES" : "NO");
        fprintf(g_logfile, "Tried to load from: ../../../assets/cues.txt\n");
        fflush(g_logfile);
    }
    if (has_image) {
        printf("  Key: %s, Path: %s\n", image_cue.asset_key, image_cue.asset_path);
        if (g_logfile) fprintf(g_logfile, "  Key: %s, Path: %s\n", image_cue.asset_key, image_cue.asset_path);
        printf("  Pos: (%.2f,%.2f), Scale: %.2f, Time: %.1f-%.1fs\n",
               image_cue.x, image_cue.y, image_cue.scale, 
               image_cue.cue_start, image_cue.cue_end);
        printf("  Curves: X=%d, Y=%d, Scale=%d, Opacity=%d\n",
               image_cue.curve_x, image_cue.curve_y, image_cue.curve_scale, image_cue.curve_opacity);
        if (g_logfile) {
            fprintf(g_logfile, "  Pos: (%.2f,%.2f), Scale: %.2f, Time: %.1f-%.1fs\n",
                   image_cue.x, image_cue.y, image_cue.scale, 
                   image_cue.cue_start, image_cue.cue_end);
            fprintf(g_logfile, "  Curves: X=%d, Y=%d, Scale=%d, Opacity=%d\n",
                   image_cue.curve_x, image_cue.curve_y, image_cue.curve_scale, image_cue.curve_opacity);
        }
    }
    
    // Load text cue
    TextCue text_cue = {};
    bool has_text = LoadTextCue(cues_path, &text_cue);
    TextTexture text_tex = {};
    bool text_loaded = false;

    // Load mesh cue
    MeshCue mesh_cue = {};
    mesh_cue.scale[0] = mesh_cue.scale[1] = mesh_cue.scale[2] = 1.0f;
    bool has_mesh = LoadMeshCue(cues_path, &mesh_cue);
    printf("Mesh cue loaded: %s\n", has_mesh ? "YES" : "NO");
    if (has_mesh) {
        printf("  Key: %s, Type: %d, Size: %.2f\n", mesh_cue.asset_key, mesh_cue.mesh_type, mesh_cue.mesh_size);
    }
    
    printf("Text cue loaded: %s\n", has_text ? "YES" : "NO");
    if (has_text) {
        printf("  Text: \"%s\", Font: %s, Size: %.0f\n", text_cue.text, text_cue.font_name, text_cue.size);
        printf("  Time: %.1f-%.1fs\n", text_cue.cue_start, text_cue.cue_end);
    }
    
    // Calculate total duration from all cues
    float total_duration = 0.0f;
    if (cue.cue_end > total_duration) total_duration = cue.cue_end;  // Shader cue
    if (has_image && image_cue.cue_end > total_duration) total_duration = image_cue.cue_end;
    if (has_text && text_cue.cue_end > total_duration) total_duration = text_cue.cue_end;
    if (has_mesh && mesh_cue.cue_end > total_duration) total_duration = mesh_cue.cue_end;
    if (has_music && music_cue.cue_end > total_duration) total_duration = music_cue.cue_end;
    
    // If no cues or all have 0 duration, use default
    if (total_duration <= 0.0f) total_duration = 10.0f;
    
    printf("Total intro duration: %.1fs\n", total_duration);
    
    // Clamp shader_scene_id to valid range
    if (cue.shader_scene_id < 0 || cue.shader_scene_id > 9) {
        cue.shader_scene_id = 0;
    }
    
    // Create window and OpenGL context
    rev::platform::WindowConfig config;
    config.width = 1920;
    config.height = 1080;
    config.fullscreen = true;
    config.title = "HiMYM - Minimal Intro Test";
    
    rev::platform::Window* window = rev::platform::CreateIntroWindow(config);
    if (!window) {
        return -1;
    }
    
    // Load OpenGL functions
    rev::platform::LoadGLFunctions();
    
    // Initialize GDI+
    Gdiplus::GdiplusStartupInput gdiplusStartupInput;
    ULONG_PTR gdiplusToken;
    Gdiplus::GdiplusStartup(&gdiplusToken, &gdiplusStartupInput, nullptr);
    
    // Load GL 3.3+ function pointers
    glGenVertexArrays = (PFNGLGENVERTEXARRAYSPROC)rev::platform::GetProcAddress("glGenVertexArrays");
    glBindVertexArray = (PFNGLBINDVERTEXARRAYPROC)rev::platform::GetProcAddress("glBindVertexArray");
    glActiveTexture = (PFNGLACTIVETEXTUREPROC)rev::platform::GetProcAddress("glActiveTexture");
    
    // Create and bind VAO (required for OpenGL 3.3 core)
    GLuint vao;
    glGenVertexArrays(1, &vao);
    glBindVertexArray(vao);
    
    // Compile shader with selected fragment shader
    const char* selected_frag_shader = fragment_shaders[cue.shader_scene_id];
    rev::shader::Program* shader = rev::shader::CompileFromSource(vertex_shader, selected_frag_shader);
    if (!shader) {
        rev::platform::DestroyIntroWindow(window);
        return -1;
    }
    
    // Compile sprite shader
    rev::shader::Program* sprite_shader = rev::shader::CompileFromSource(sprite_vertex_shader, sprite_fragment_shader);
    if (!sprite_shader) {
        printf("ERROR: Sprite shader failed to compile\n");
    } else {
        printf("Sprite shader OK\n");
    }

    // Compile mesh shader
    rev::shader::Program* mesh_shader = nullptr;
    rev::mesh::Mesh* mesh_obj = nullptr;
    if (has_mesh) {
        mesh_shader = rev::shader::CompileFromSource(mesh_vertex_shader_src, mesh_fragment_shader_src);
        if (!mesh_shader) {
            printf("ERROR: Mesh shader failed to compile\n");
        } else {
            printf("Mesh shader OK\n");
        }

        float size  = mesh_cue.mesh_size  > 0.0f ? mesh_cue.mesh_size  : 1.0f;
        float param = mesh_cue.mesh_param > 0.0f ? mesh_cue.mesh_param : 16.0f;
        switch (mesh_cue.mesh_type) {
            case 0: mesh_obj = rev::mesh::CreateCube(size); break;
            case 1: mesh_obj = rev::mesh::CreateSphere(size, (int)param); break;
            case 2: mesh_obj = rev::mesh::CreatePlane(size, param > 0.0f ? param : size); break;
            case 3: mesh_obj = rev::mesh::CreateTorus(size, param > 0.0f ? param : 0.3f, 32, 16); break;
            case 4: {
                // External glTF/GLB — loaded via rev_gltf
#if defined(REV_GLTF_AVAILABLE)
#ifdef HIMYM_PACKED_ASSETS
                {
                    const rev::pack::PackedAsset* pa = rev::pack::GetPackedAsset(
                        mesh_cue.asset_key, kPackedAssets, kPackedAssetCount);
                    if (pa) {
                        // Extract textures to current directory (project workspace when launched by editor)
                        rev::gltf::ImportResult* ir = rev::gltf::LoadMeshFromMemory(pa->data, pa->size, ".");
                        if (ir && ir->ok) {
                            mesh_obj = ir->mesh;
                            ir->mesh = nullptr;
                            
                            // Load base color texture if present
                            if (ir->material.base_color_texture[0] != '\0') {
                                rev::runtime::ImageTexture tex{};
                                if (rev::runtime::LoadImageTexture(ir->material.base_color_texture, &tex)) {
                                    mesh_obj->base_color_texture = tex.texture_id;
                                    printf("Loaded mesh texture (packed): %s\n", ir->material.base_color_texture);
                                } else {
                                    printf("Failed to load texture (packed): %s\n", ir->material.base_color_texture);
                                }
                            }
                            
                            // Transfer animations to mesh
                            if (ir->animation_count > 0) {
                                mesh_obj->animation_data = ir->animations;
                                mesh_obj->animation_count = ir->animation_count;
                                mesh_obj->current_animation = 0;  // Start first animation
                                mesh_obj->animation_time = 0.0f;
                                mesh_obj->animation_speed = 1.0f;
                                mesh_obj->animation_loop = true;
                                ir->animations = nullptr;  // Transfer ownership
                                printf("glTF loaded (packed): %s with %d animations\n", mesh_cue.asset_key, ir->animation_count);
                            } else {
                                printf("glTF loaded (packed): %s\n", mesh_cue.asset_key);
                            }
                        } else {
                            printf("glTF load failed (packed): %s\n", (ir ? ir->error : "null result"));
                            mesh_obj = rev::mesh::CreateCube(1.0f);
                        }
                        if (ir) rev::gltf::FreeImportResult(ir);
                    } else {
                        printf("Packed mesh asset not found: %s — using cube fallback\n", mesh_cue.asset_key);
                        mesh_obj = rev::mesh::CreateCube(1.0f);
                    }
                }
#else
                {
                    // Extract textures to the same directory as the mesh file
                    char mesh_dir[512] = {};
                    strncpy_s(mesh_dir, mesh_cue.asset_path, sizeof(mesh_dir) - 1);
                    char* last_slash = strrchr(mesh_dir, '\\');
                    if (!last_slash) last_slash = strrchr(mesh_dir, '/');
                    if (last_slash) *last_slash = '\0'; else mesh_dir[0] = '\0';
                    
                    rev::gltf::ImportResult* ir = rev::gltf::LoadMesh(mesh_cue.asset_path, mesh_dir[0] ? mesh_dir : ".");
                    if (ir && ir->ok) {
                        mesh_obj = ir->mesh;
                        ir->mesh = nullptr;
                        
                        // Load base color texture if present
                        if (ir->material.base_color_texture[0] != '\0') {
                            rev::runtime::ImageTexture tex{};
                            if (rev::runtime::LoadImageTexture(ir->material.base_color_texture, &tex)) {
                                mesh_obj->base_color_texture = tex.texture_id;
                                printf("Loaded mesh texture: %s\n", ir->material.base_color_texture);
                            }
                        }
                        
                        // Transfer animations to mesh
                        if (ir->animation_count > 0) {
                            mesh_obj->animation_data = ir->animations;
                            mesh_obj->animation_count = ir->animation_count;
                            mesh_obj->current_animation = 0;  // Start first animation
                            mesh_obj->animation_time = 0.0f;
                            mesh_obj->animation_speed = 1.0f;
                            mesh_obj->animation_loop = true;
                            ir->animations = nullptr;  // Transfer ownership
                            printf("glTF loaded: %s with %d animations\n", mesh_cue.asset_path, ir->animation_count);
                        } else {
                            printf("glTF loaded: %s\n", mesh_cue.asset_path);
                        }
                    } else {
                        printf("glTF load failed: %s\n", (ir ? ir->error : "null result"));
                        mesh_obj = rev::mesh::CreateCube(1.0f);
                    }
                    if (ir) rev::gltf::FreeImportResult(ir);
                }
#endif
#else
                printf("mesh_type=4 (glTF) not available in this build — using cube fallback\n");
                mesh_obj = rev::mesh::CreateCube(1.0f);
#endif
                break;
            }
            default: mesh_obj = rev::mesh::CreateCube(1.0f); break;
        }
        if (mesh_obj) {
            rev::mesh::UploadToGPU(mesh_obj);
            printf("Mesh created: type=%d size=%.2f\n", mesh_cue.mesh_type, size);
        }
    }
    
    // Get uniform locations
    int u_time_loc = rev::shader::GetUniformLocation(shader, "u_time");
    int u_resolution_loc = rev::shader::GetUniformLocation(shader, "u_resolution");
    int u_palette_low_loc = rev::shader::GetUniformLocation(shader, "u_palette_low");
    int u_palette_mid_loc = rev::shader::GetUniformLocation(shader, "u_palette_mid");
    int u_palette_high_loc = rev::shader::GetUniformLocation(shader, "u_palette_high");
    int u_speed_loc = rev::shader::GetUniformLocation(shader, "u_speed");
    int u_intensity_loc = rev::shader::GetUniformLocation(shader, "u_intensity");
    int u_warp_loc = rev::shader::GetUniformLocation(shader, "u_warp");
    
    // Load XM music if available
    rev::xm::Player* xm_player = nullptr;
    if (has_music && music_cue.asset_key[0] != '\0') {
#ifdef HIMYM_PACKED_ASSETS
        // Load from embedded data
        const rev::pack::PackedAsset* pa = rev::pack::GetPackedAsset(music_cue.asset_key, kPackedAssets, kPackedAssetCount);
        if (pa) {
            xm_player = rev::xm::CreatePlayer(pa->data, (long)pa->size);
            if (xm_player)
                printf("Loaded music (packed): %s\n", music_cue.asset_key);
        }
#else
        char music_path[512];
        strncpy_s(music_path, music_cue.asset_path, _TRUNCATE);

        FILE* xm_file = nullptr;
        fopen_s(&xm_file, music_path, "rb");
        if (xm_file) {
            fseek(xm_file, 0, SEEK_END);
            long xm_size = ftell(xm_file);
            fseek(xm_file, 0, SEEK_SET);

            unsigned char* xm_data = new unsigned char[xm_size];
            fread(xm_data, 1, xm_size, xm_file);
            fclose(xm_file);

            xm_player = rev::xm::CreatePlayer(xm_data, xm_size);
            delete[] xm_data;

            if (xm_player)
                printf("Loaded music: %s (start: %.2f, end: %.2f)\n",
                       music_cue.asset_key, music_cue.cue_start, music_cue.cue_end);
        }
#endif
    }
    
    // Load image texture
    if (has_image && image_cue.asset_key[0] != '\0') {
#ifdef HIMYM_PACKED_ASSETS
        if (g_logfile) fprintf(g_logfile, "[Packed] Looking up asset: %s (table count=%d)\n", image_cue.asset_key, kPackedAssetCount);
        const rev::pack::PackedAsset* pa = rev::pack::GetPackedAsset(image_cue.asset_key, kPackedAssets, kPackedAssetCount);
        if (pa) {
            if (g_logfile) fprintf(g_logfile, "[Packed] Found asset: %s size=%zu, calling LoadImageTextureFromMemory\n", pa->key, pa->size);
            if (LoadImageTextureFromMemory(pa->data, pa->size, &image_tex)) {
                image_loaded = true;
                printf("Image loaded (packed): %s %dx%d\n", image_cue.asset_key, image_tex.width, image_tex.height);
                if (g_logfile) fprintf(g_logfile, "[Packed] Image loaded: %s %dx%d\n", image_cue.asset_key, image_tex.width, image_tex.height);
            } else {
                printf("FAILED to load packed image: %s\n", image_cue.asset_key);
                if (g_logfile) fprintf(g_logfile, "[Packed] FAILED to load image from memory: %s\n", image_cue.asset_key);
            }
        } else {
            printf("Packed asset not found: %s\n", image_cue.asset_key);
            if (g_logfile) {
                fprintf(g_logfile, "[Packed] Asset NOT found: %s\n", image_cue.asset_key);
                fprintf(g_logfile, "[Packed] Available keys (%d):\n", kPackedAssetCount);
                for (int _i = 0; _i < kPackedAssetCount; ++_i)
                    fprintf(g_logfile, "  [%d] %s\n", _i, kPackedAssets[_i].key ? kPackedAssets[_i].key : "(null)");
            }
        }
        if (g_logfile) fflush(g_logfile);
#else
        // asset_path is workspace-root-relative (e.g. "project_assets/logo.png")
        // Working directory is always workspace root (whether launched from editor or start script)
        char image_path[512];
        strncpy_s(image_path, image_cue.asset_path, _TRUNCATE);

        // Convert forward slashes to backslashes for Windows GDI+
        for (char* p = image_path; *p; ++p) {
            if (*p == '/') *p = '\\';
        }

        printf("\nLoading image texture: %s\n", image_path);
        if (g_logfile) fprintf(g_logfile, "\nLoading image texture: %s\n", image_path);
        if (LoadImageTexture(image_path, &image_tex)) {
            image_loaded = true;
            printf("Image loaded: %dx%d, will show at %.1f-%.1fs\n",
                   image_tex.width, image_tex.height,
                   image_cue.cue_start, image_cue.cue_end);
            if (g_logfile) fprintf(g_logfile, "Image loaded: %dx%d, will show at %.1f-%.1fs\n",
                   image_tex.width, image_tex.height,
                   image_cue.cue_start, image_cue.cue_end);
        } else {
            printf("FAILED to load image\n");
            if (g_logfile) fprintf(g_logfile, "FAILED to load image from: %s\n", image_path);
        }
#endif
    }
    
    // Render text to texture
    if (has_text && text_cue.text[0] != '\0') {
        printf("\nRendering text: \"%s\"\n", text_cue.text);
        if (RenderTextToTexture(text_cue.text, text_cue.font_name, text_cue.size,
                                text_cue.color.r, text_cue.color.g, text_cue.color.b, &text_tex)) {
            text_loaded = true;
            printf("Text rendered: %dx%d, will show at %.1f-%.1fs\n",
                   text_tex.width, text_tex.height,
                   text_cue.cue_start, text_cue.cue_end);
        } else {
            printf("FAILED to render text\n");
        }
    }
    
    // Start audio thread
    AudioState* audio_state = nullptr;
    HANDLE audio_thread = nullptr;
    if (xm_player) {
        WAVEFORMATEX wfx = {};
        wfx.wFormatTag      = WAVE_FORMAT_PCM;
        wfx.nChannels       = (WORD)kAudioChannels;
        wfx.nSamplesPerSec  = kAudioSampleRate;
        wfx.wBitsPerSample  = 16;
        wfx.nBlockAlign     = wfx.nChannels * wfx.wBitsPerSample / 8;
        wfx.nAvgBytesPerSec = wfx.nSamplesPerSec * wfx.nBlockAlign;

        audio_state = new AudioState();
        memset(audio_state, 0, sizeof(AudioState));
        audio_state->player = xm_player;
        audio_state->stop   = false;

        if (waveOutOpen(&audio_state->wave_out, WAVE_MAPPER, &wfx, 0, 0, CALLBACK_NULL) == MMSYSERR_NOERROR) {
            audio_thread = CreateThread(nullptr, 0, AudioThreadProc, audio_state, 0, nullptr);
            printf("Audio started: %d Hz stereo\n", kAudioSampleRate);
        } else {
            printf("ERROR: waveOutOpen failed\n");
            delete audio_state;
            audio_state = nullptr;
        }
    }

    // Main loop
    double start_time = rev::platform::GetTime();
    double prev_time = start_time;

    while (rev::platform::PollEvents(window) && !window->should_close) {
        double current_time = rev::platform::GetTime();
        float time = static_cast<float>(current_time - start_time);
        float dt = static_cast<float>(current_time - prev_time);
        prev_time = current_time;
        
        // Image activation/deactivation logging
        static bool image_was_active = false;
        bool image_active_now = (image_loaded && time >= image_cue.cue_start && time <= image_cue.cue_end);
        if (image_active_now && !image_was_active) {
            printf("[%.1fs] IMAGE ON (sprite_shader=%p)\n", time, sprite_shader);
            image_was_active = true;
        } else if (!image_active_now && image_was_active) {
            printf("[%.1fs] IMAGE OFF\n", time);
            image_was_active = false;
        }
        
        // Clear the full physical window (letterbox bars go black too)
        int ww = window->win_width  > 0 ? window->win_width  : config.width;
        int wh = window->win_height > 0 ? window->win_height : config.height;
        glViewport(0, 0, ww, wh);
        glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);

        // Letterbox viewport: fit render resolution centered in the actual window.
        // NDC calculations throughout still use config.width/height (1920×1080).
        {
            float ta = (float)config.width / (float)config.height;
            float wa = (float)ww / (float)wh;
            int vx = 0, vy = 0, vw = ww, vh = wh;
            if (wa > ta) { vw = (int)((float)vh * ta + 0.5f); vx = (ww - vw) / 2; }
            else         { vh = (int)((float)vw / ta + 0.5f); vy = (wh - vh) / 2; }
            glViewport(vx, vy, vw, vh);
        }

        // Rebind the global VAO: rev::mesh::UploadToGPU / Render leave the mesh VAO
        // (or VAO 0) current, but the background fullscreen quad requires a valid VAO
        // in OpenGL 3.3 core profile (vertex shader only uses gl_VertexID, no attribs).
        glBindVertexArray(vao);

        // Use shader and set uniforms
        rev::shader::Use(shader);
        rev::shader::SetFloat(shader, u_time_loc, time);
        rev::shader::SetVec2(shader, u_resolution_loc, 
                            static_cast<float>(config.width), 
                            static_cast<float>(config.height));
        
        // Evaluate shader curves
        float elapsed_time = time - cue.cue_start;
        float anim_palette_low[3] = {cue.palette_low[0], cue.palette_low[1], cue.palette_low[2]};
        float anim_palette_mid[3] = {cue.palette_mid[0], cue.palette_mid[1], cue.palette_mid[2]};
        float anim_palette_high[3] = {cue.palette_high[0], cue.palette_high[1], cue.palette_high[2]};
        float anim_speed = cue.speed;
        float anim_intensity = cue.intensity;
        float anim_warp = cue.warp;
        
        if (elapsed_time >= 0.0f) {
            if (cue.curve_palette_low_r >= 0 && cue.curve_palette_low_r < curve_count) {
                float t = elapsed_time / curves[cue.curve_palette_low_r].duration;
                anim_palette_low[0] = rev::curve::Evaluate(curves[cue.curve_palette_low_r], t);
            }
            if (cue.curve_palette_low_g >= 0 && cue.curve_palette_low_g < curve_count) {
                float t = elapsed_time / curves[cue.curve_palette_low_g].duration;
                anim_palette_low[1] = rev::curve::Evaluate(curves[cue.curve_palette_low_g], t);
            }
            if (cue.curve_palette_low_b >= 0 && cue.curve_palette_low_b < curve_count) {
                float t = elapsed_time / curves[cue.curve_palette_low_b].duration;
                anim_palette_low[2] = rev::curve::Evaluate(curves[cue.curve_palette_low_b], t);
            }
            if (cue.curve_palette_mid_r >= 0 && cue.curve_palette_mid_r < curve_count) {
                float t = elapsed_time / curves[cue.curve_palette_mid_r].duration;
                anim_palette_mid[0] = rev::curve::Evaluate(curves[cue.curve_palette_mid_r], t);
            }
            if (cue.curve_palette_mid_g >= 0 && cue.curve_palette_mid_g < curve_count) {
                float t = elapsed_time / curves[cue.curve_palette_mid_g].duration;
                anim_palette_mid[1] = rev::curve::Evaluate(curves[cue.curve_palette_mid_g], t);
            }
            if (cue.curve_palette_mid_b >= 0 && cue.curve_palette_mid_b < curve_count) {
                float t = elapsed_time / curves[cue.curve_palette_mid_b].duration;
                anim_palette_mid[2] = rev::curve::Evaluate(curves[cue.curve_palette_mid_b], t);
            }
            if (cue.curve_palette_high_r >= 0 && cue.curve_palette_high_r < curve_count) {
                float t = elapsed_time / curves[cue.curve_palette_high_r].duration;
                anim_palette_high[0] = rev::curve::Evaluate(curves[cue.curve_palette_high_r], t);
            }
            if (cue.curve_palette_high_g >= 0 && cue.curve_palette_high_g < curve_count) {
                float t = elapsed_time / curves[cue.curve_palette_high_g].duration;
                anim_palette_high[1] = rev::curve::Evaluate(curves[cue.curve_palette_high_g], t);
            }
            if (cue.curve_palette_high_b >= 0 && cue.curve_palette_high_b < curve_count) {
                float t = elapsed_time / curves[cue.curve_palette_high_b].duration;
                anim_palette_high[2] = rev::curve::Evaluate(curves[cue.curve_palette_high_b], t);
            }
            if (cue.curve_speed >= 0 && cue.curve_speed < curve_count) {
                float t = elapsed_time / curves[cue.curve_speed].duration;
                anim_speed = rev::curve::Evaluate(curves[cue.curve_speed], t);
            }
            if (cue.curve_intensity >= 0 && cue.curve_intensity < curve_count) {
                float t = elapsed_time / curves[cue.curve_intensity].duration;
                anim_intensity = rev::curve::Evaluate(curves[cue.curve_intensity], t);
            }
            if (cue.curve_warp >= 0 && cue.curve_warp < curve_count) {
                float t = elapsed_time / curves[cue.curve_warp].duration;
                anim_warp = rev::curve::Evaluate(curves[cue.curve_warp], t);
            }
            // Note: exposure_ramp, fade_ramp, opacity curves not used in runtime shaders yet
        }
        
        // Set palette and parameter uniforms (using animated values)
        if (u_palette_low_loc >= 0)
            rev::shader::SetVec3(shader, u_palette_low_loc, anim_palette_low[0], anim_palette_low[1], anim_palette_low[2]);
        if (u_palette_mid_loc >= 0)
            rev::shader::SetVec3(shader, u_palette_mid_loc, anim_palette_mid[0], anim_palette_mid[1], anim_palette_mid[2]);
        if (u_palette_high_loc >= 0)
            rev::shader::SetVec3(shader, u_palette_high_loc, anim_palette_high[0], anim_palette_high[1], anim_palette_high[2]);
        if (u_speed_loc >= 0)
            rev::shader::SetFloat(shader, u_speed_loc, anim_speed);
        if (u_intensity_loc >= 0)
            rev::shader::SetFloat(shader, u_intensity_loc, anim_intensity);
        if (u_warp_loc >= 0)
            rev::shader::SetFloat(shader, u_warp_loc, anim_warp);
        
        // Draw fullscreen quad (shader background)
        glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
        
        // --- Unified layered draw pass ---
        // Collect active image/text/mesh cues, sort by layer_order, draw in order.
        {
            struct DrawEntry { int type; int layer; }; // 0=image 1=text 2=mesh
            DrawEntry entries[3]; int ne = 0;

            bool img_active = sprite_shader && image_loaded
                              && time >= image_cue.cue_start && time <= image_cue.cue_end;
            bool txt_active = sprite_shader && text_loaded
                              && time >= text_cue.cue_start  && time <= text_cue.cue_end;
            bool msh_active = mesh_shader && mesh_obj && has_mesh
                              && time >= mesh_cue.cue_start && time <= mesh_cue.cue_end;

            if (img_active) entries[ne++] = {0, image_cue.layer_order};
            if (txt_active) entries[ne++] = {1, text_cue.layer_order};
            if (msh_active) entries[ne++] = {2, mesh_cue.layer_order};

            // Bubble sort ascending (lower layer_order draws first = further back)
            for (int i = 0; i < ne - 1; i++)
                for (int j = 0; j < ne - i - 1; j++)
                    if (entries[j].layer > entries[j+1].layer) {
                        DrawEntry tmp = entries[j]; entries[j] = entries[j+1]; entries[j+1] = tmp;
                    }

            bool blend_on = false, depth_on = false;

            for (int ei = 0; ei < ne; ei++) {
                if (entries[ei].type == 0) {
                    // Image sprite
                    if (!blend_on) {
                        glDisable(GL_DEPTH_TEST);
                        glDepthMask(GL_FALSE);  // Disable depth writes for sprites
                        glEnable(GL_BLEND);
                        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
                        blend_on = true; depth_on = false;
                    }
                    rev::shader::Use(sprite_shader);
                    
                    // Evaluate curves for animation
                    float anim_x = image_cue.x;
                    float anim_y = image_cue.y;
                    float anim_scale = image_cue.scale;
                    float anim_opacity = image_cue.opacity;
                    
                    float elapsed_time = time - image_cue.cue_start;
                    if (elapsed_time >= 0.0f) {
                        if (image_cue.curve_x >= 0 && image_cue.curve_x < curve_count) {
                            float t = elapsed_time / curves[image_cue.curve_x].duration;
                            anim_x = rev::curve::Evaluate(curves[image_cue.curve_x], t);
                            
                            // Debug logging (first 5 frames only)
                            static int log_count = 0;
                            if (g_logfile && log_count < 5) {
                                fprintf(g_logfile, "[Frame %d] time=%.2f, elapsed=%.2f, t=%.3f, anim_x=%.3f (base=%.3f)\n",
                                    log_count, time, elapsed_time, t, anim_x, image_cue.x);
                                log_count++;
                            }
                        }
                        if (image_cue.curve_y >= 0 && image_cue.curve_y < curve_count) {
                            float t = elapsed_time / curves[image_cue.curve_y].duration;
                            anim_y = rev::curve::Evaluate(curves[image_cue.curve_y], t);
                        }
                        if (image_cue.curve_scale >= 0 && image_cue.curve_scale < curve_count) {
                            float t = elapsed_time / curves[image_cue.curve_scale].duration;
                            anim_scale = rev::curve::Evaluate(curves[image_cue.curve_scale], t);
                        }
                        if (image_cue.curve_opacity >= 0 && image_cue.curve_opacity < curve_count) {
                            float t = elapsed_time / curves[image_cue.curve_opacity].duration;
                            anim_opacity = rev::curve::Evaluate(curves[image_cue.curve_opacity], t);
                        }
                    }
                    
                    float w = (image_tex.width  * anim_scale) / (float)config.width  * 2.0f;
                    float h = (image_tex.height * anim_scale) / (float)config.height * 2.0f;
                    float x =  (anim_x * 2.0f - 1.0f);
                    float y = -((anim_y * 2.0f) - 1.0f);
                    int u_pos = rev::shader::GetUniformLocation(sprite_shader, "u_position");
                    int u_sz  = rev::shader::GetUniformLocation(sprite_shader, "u_size");
                    int u_tex = rev::shader::GetUniformLocation(sprite_shader, "u_texture");
                    int u_opa = rev::shader::GetUniformLocation(sprite_shader, "u_opacity");
                    if (u_pos >= 0) rev::shader::SetVec2(sprite_shader, u_pos, x, y);
                    if (u_sz  >= 0) rev::shader::SetVec2(sprite_shader, u_sz, w, h);
                    if (u_tex >= 0) rev::shader::SetInt(sprite_shader, u_tex, 0);
                    if (u_opa >= 0) rev::shader::SetFloat(sprite_shader, u_opa,
                        anim_opacity * ComputeEffectOpacity(
                            image_cue.effect_type, image_cue.fade_in_start, image_cue.fade_in_end,
                            image_cue.fade_out_start, image_cue.fade_out_end, time));
                    if (glActiveTexture) glActiveTexture(GL_TEXTURE0);
                    glBindTexture(GL_TEXTURE_2D, image_tex.texture_id);
                    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);

                } else if (entries[ei].type == 1) {
                    // Text sprite
                    if (!blend_on) {
                        glDisable(GL_DEPTH_TEST);
                        glDepthMask(GL_FALSE);  // Disable depth writes for sprites
                        glEnable(GL_BLEND);
                        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
                        blend_on = true; depth_on = false;
                    }
                    rev::shader::Use(sprite_shader);
                    
                    // Curve evaluation for text
                    float elapsed_time = time - text_cue.cue_start;
                    float anim_text_x = text_cue.x;
                    float anim_text_y = text_cue.y;
                    float anim_text_size = text_cue.size;
                    float anim_text_color_r = text_cue.color.r;
                    float anim_text_color_g = text_cue.color.g;
                    float anim_text_color_b = text_cue.color.b;
                    
                    if (elapsed_time >= 0.0f) {
                        if (text_cue.curve_x >= 0 && text_cue.curve_x < curve_count) {
                            float t = elapsed_time / curves[text_cue.curve_x].duration;
                            anim_text_x = rev::curve::Evaluate(curves[text_cue.curve_x], t);
                        }
                        if (text_cue.curve_y >= 0 && text_cue.curve_y < curve_count) {
                            float t = elapsed_time / curves[text_cue.curve_y].duration;
                            anim_text_y = rev::curve::Evaluate(curves[text_cue.curve_y], t);
                        }
                        // Note: Size and color curves would require re-rendering text texture
                        // Currently using base text_tex rendered at load time
                        if (text_cue.curve_size >= 0 && text_cue.curve_size < curve_count) {
                            float t = elapsed_time / curves[text_cue.curve_size].duration;
                            anim_text_size = rev::curve::Evaluate(curves[text_cue.curve_size], t);
                        }
                        if (text_cue.curve_color_r >= 0 && text_cue.curve_color_r < curve_count) {
                            float t = elapsed_time / curves[text_cue.curve_color_r].duration;
                            anim_text_color_r = rev::curve::Evaluate(curves[text_cue.curve_color_r], t);
                        }
                        if (text_cue.curve_color_g >= 0 && text_cue.curve_color_g < curve_count) {
                            float t = elapsed_time / curves[text_cue.curve_color_g].duration;
                            anim_text_color_g = rev::curve::Evaluate(curves[text_cue.curve_color_g], t);
                        }
                        if (text_cue.curve_color_b >= 0 && text_cue.curve_color_b < curve_count) {
                            float t = elapsed_time / curves[text_cue.curve_color_b].duration;
                            anim_text_color_b = rev::curve::Evaluate(curves[text_cue.curve_color_b], t);
                        }
                    }
                    
                    float size_scale = anim_text_size / text_cue.size;  // Scale based on size curve
                    float w = ((float)text_tex.width  * size_scale) / (float)config.width  * 2.0f;
                    float h = ((float)text_tex.height * size_scale) / (float)config.height * 2.0f;
                    float x =  (anim_text_x * 2.0f - 1.0f);
                    float y = -((anim_text_y * 2.0f) - 1.0f);
                    float opacity = ComputeEffectOpacity(text_cue.effect_type,
                        text_cue.fade_in_start, text_cue.fade_in_end,
                        text_cue.fade_out_start, text_cue.fade_out_end, time);
                    int u_pos = rev::shader::GetUniformLocation(sprite_shader, "u_position");
                    int u_sz  = rev::shader::GetUniformLocation(sprite_shader, "u_size");
                    int u_tex = rev::shader::GetUniformLocation(sprite_shader, "u_texture");
                    int u_opa = rev::shader::GetUniformLocation(sprite_shader, "u_opacity");
                    int u_col = rev::shader::GetUniformLocation(sprite_shader, "u_color_tint");
                    if (u_pos >= 0) rev::shader::SetVec2(sprite_shader, u_pos, x, y);
                    if (u_sz  >= 0) rev::shader::SetVec2(sprite_shader, u_sz, w, h);
                    if (u_tex >= 0) rev::shader::SetInt(sprite_shader, u_tex, 0);
                    if (u_opa >= 0) rev::shader::SetFloat(sprite_shader, u_opa, opacity);
                    if (u_col >= 0) rev::shader::SetVec3(sprite_shader, u_col, anim_text_color_r, anim_text_color_g, anim_text_color_b);
                    if (glActiveTexture) glActiveTexture(GL_TEXTURE0);
                    glBindTexture(GL_TEXTURE_2D, text_tex.texture_id);
                    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);

                } else {
                    // 3D mesh
                    if (blend_on) { glDisable(GL_BLEND); blend_on = false; }
                    if (!depth_on) {
                        glEnable(0x0B71);        // GL_DEPTH_TEST
                        glDepthMask(GL_TRUE);    // Enable depth writes for meshes
                        glClear(0x00000100);     // GL_DEPTH_BUFFER_BIT
                        depth_on = true;
                    }
                    rev::shader::Use(mesh_shader);
                    
                    // Animated transform (start with cue values)
                    float anim_pos[3] = {mesh_cue.pos[0], mesh_cue.pos[1], mesh_cue.pos[2]};
                    float anim_rot[3] = {mesh_cue.rot[0], mesh_cue.rot[1], mesh_cue.rot[2]};
                    float anim_scale[3] = {mesh_cue.scale[0], mesh_cue.scale[1], mesh_cue.scale[2]};
                    float anim_color[4] = {mesh_cue.color[0], mesh_cue.color[1], mesh_cue.color[2], mesh_cue.color[3]};
                    float anim_mesh_size = mesh_cue.mesh_size;
                    float anim_metallic = mesh_cue.metallic;
                    float anim_roughness = mesh_cue.roughness;
                    
                    // Curve evaluation for mesh
                    float elapsed_time = time - mesh_cue.cue_start;
                    if (elapsed_time >= 0.0f) {
                        if (mesh_cue.curve_pos_x >= 0 && mesh_cue.curve_pos_x < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_pos_x].duration;
                            anim_pos[0] = rev::curve::Evaluate(curves[mesh_cue.curve_pos_x], t);
                        }
                        if (mesh_cue.curve_pos_y >= 0 && mesh_cue.curve_pos_y < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_pos_y].duration;
                            anim_pos[1] = rev::curve::Evaluate(curves[mesh_cue.curve_pos_y], t);
                        }
                        if (mesh_cue.curve_pos_z >= 0 && mesh_cue.curve_pos_z < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_pos_z].duration;
                            anim_pos[2] = rev::curve::Evaluate(curves[mesh_cue.curve_pos_z], t);
                        }
                        if (mesh_cue.curve_rot_x >= 0 && mesh_cue.curve_rot_x < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_rot_x].duration;
                            anim_rot[0] = rev::curve::Evaluate(curves[mesh_cue.curve_rot_x], t);
                        }
                        if (mesh_cue.curve_rot_y >= 0 && mesh_cue.curve_rot_y < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_rot_y].duration;
                            anim_rot[1] = rev::curve::Evaluate(curves[mesh_cue.curve_rot_y], t);
                        }
                        if (mesh_cue.curve_rot_z >= 0 && mesh_cue.curve_rot_z < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_rot_z].duration;
                            anim_rot[2] = rev::curve::Evaluate(curves[mesh_cue.curve_rot_z], t);
                        }
                        if (mesh_cue.curve_scale_x >= 0 && mesh_cue.curve_scale_x < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_scale_x].duration;
                            anim_scale[0] = rev::curve::Evaluate(curves[mesh_cue.curve_scale_x], t);
                        }
                        if (mesh_cue.curve_scale_y >= 0 && mesh_cue.curve_scale_y < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_scale_y].duration;
                            anim_scale[1] = rev::curve::Evaluate(curves[mesh_cue.curve_scale_y], t);
                        }
                        if (mesh_cue.curve_scale_z >= 0 && mesh_cue.curve_scale_z < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_scale_z].duration;
                            anim_scale[2] = rev::curve::Evaluate(curves[mesh_cue.curve_scale_z], t);
                        }
                        if (mesh_cue.curve_color_r >= 0 && mesh_cue.curve_color_r < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_color_r].duration;
                            anim_color[0] = rev::curve::Evaluate(curves[mesh_cue.curve_color_r], t);
                        }
                        if (mesh_cue.curve_color_g >= 0 && mesh_cue.curve_color_g < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_color_g].duration;
                            anim_color[1] = rev::curve::Evaluate(curves[mesh_cue.curve_color_g], t);
                        }
                        if (mesh_cue.curve_color_b >= 0 && mesh_cue.curve_color_b < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_color_b].duration;
                            anim_color[2] = rev::curve::Evaluate(curves[mesh_cue.curve_color_b], t);
                        }
                        if (mesh_cue.curve_color_a >= 0 && mesh_cue.curve_color_a < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_color_a].duration;
                            anim_color[3] = rev::curve::Evaluate(curves[mesh_cue.curve_color_a], t);
                        }
                        if (mesh_cue.curve_mesh_size >= 0 && mesh_cue.curve_mesh_size < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_mesh_size].duration;
                            anim_mesh_size = rev::curve::Evaluate(curves[mesh_cue.curve_mesh_size], t);
                        }
                        if (mesh_cue.curve_metallic >= 0 && mesh_cue.curve_metallic < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_metallic].duration;
                            anim_metallic = rev::curve::Evaluate(curves[mesh_cue.curve_metallic], t);
                        }
                        if (mesh_cue.curve_roughness >= 0 && mesh_cue.curve_roughness < curve_count) {
                            float t = elapsed_time / curves[mesh_cue.curve_roughness].duration;
                            anim_roughness = rev::curve::Evaluate(curves[mesh_cue.curve_roughness], t);
                        }
                    }
                    
                    // Update and apply animation if present
#if defined(REV_GLTF_AVAILABLE)
                    if (mesh_obj->current_animation >= 0) {
                        // Update animation time
                        rev::gltf::UpdateMeshAnimation(mesh_obj, dt);
                        
                        // Evaluate animation at current time
                        rev::gltf::Animation* anims = (rev::gltf::Animation*)mesh_obj->animation_data;
                        if (anims) {
                            float translation[3], rotation[4], scale[3];
                            rev::gltf::EvaluateAnimation(&anims[mesh_obj->current_animation],
                                                        mesh_obj->animation_time,
                                                        translation, rotation, scale);
                            // Apply animation transform on top of cue transform
                            rev::gltf::ApplyAnimationTransform(anim_pos, anim_rot, anim_scale,
                                                              translation, rotation, scale);
                        }
                    }
#endif
                    
                    float aspect = (float)config.width / (float)config.height;
                    float eye[3]    = {0.0f, 0.0f, 5.0f};
                    float center[3] = {0.0f, 0.0f, 0.0f};
                    float up_v[3]   = {0.0f, 1.0f, 0.0f};
                    float view_mat[16], proj_mat[16], model_mat[16];
                    Mat4Perspective(proj_mat, 3.14159265f * 0.25f, aspect, 0.1f, 100.0f);
                    Mat4LookAt(view_mat, eye, center, up_v);
                    Mat4Model(model_mat, anim_pos, anim_rot, anim_scale);  // Use animated transform
                    typedef void (*PFNGLUNIFORMMATRIX4FVPROC)(int, int, unsigned char, const float*);
                    auto glUniformMatrix4fv_fn = (PFNGLUNIFORMMATRIX4FVPROC)wglGetProcAddress("glUniformMatrix4fv");
                    if (glUniformMatrix4fv_fn) {
                        glUniformMatrix4fv_fn(rev::shader::GetUniformLocation(mesh_shader,"u_model"), 1,0,model_mat);
                        glUniformMatrix4fv_fn(rev::shader::GetUniformLocation(mesh_shader,"u_view"),  1,0,view_mat);
                        glUniformMatrix4fv_fn(rev::shader::GetUniformLocation(mesh_shader,"u_projection"),1,0,proj_mat);
                    }
                    float light_pos[3] = {3.0f, 5.0f, 4.0f};
                    int loc_light = rev::shader::GetUniformLocation(mesh_shader, "u_light_pos");
                    int loc_vpos  = rev::shader::GetUniformLocation(mesh_shader, "u_view_pos");
                    int loc_color = rev::shader::GetUniformLocation(mesh_shader, "u_color");
                    int loc_metal = rev::shader::GetUniformLocation(mesh_shader, "u_metallic");
                    int loc_rough = rev::shader::GetUniformLocation(mesh_shader, "u_roughness");
                    if (loc_light >= 0) rev::shader::SetVec3(mesh_shader, loc_light, light_pos[0], light_pos[1], light_pos[2]);
                    if (loc_vpos  >= 0) rev::shader::SetVec3(mesh_shader, loc_vpos, eye[0], eye[1], eye[2]);
                    if (loc_color >= 0) {
                        typedef void (*PFNGLUNIFORM4FVPROC)(int, int, const float*);
                        auto glUniform4fv_fn = (PFNGLUNIFORM4FVPROC)wglGetProcAddress("glUniform4fv");
                        if (glUniform4fv_fn) {
                            float opa = ComputeEffectOpacity(mesh_cue.effect_type,
                                mesh_cue.fade_in_start, mesh_cue.fade_in_end,
                                mesh_cue.fade_out_start, mesh_cue.fade_out_end, time);
                            float col[4] = {anim_color[0], anim_color[1], anim_color[2], anim_color[3]*opa};
                            glUniform4fv_fn(loc_color, 1, col);
                        }
                    }
                    if (loc_metal >= 0) rev::shader::SetFloat(mesh_shader, loc_metal, anim_metallic);
                    if (loc_rough >= 0) rev::shader::SetFloat(mesh_shader, loc_rough, anim_roughness);
                    
                    // Bind texture if available
                    int loc_has_tex = rev::shader::GetUniformLocation(mesh_shader, "u_has_texture");
                    if (mesh_obj->base_color_texture != 0) {
                        glBindTexture(0x0DE1, mesh_obj->base_color_texture); // GL_TEXTURE_2D = 0x0DE1
                        int loc_tex = rev::shader::GetUniformLocation(mesh_shader, "u_base_color_texture");
                        if (loc_tex >= 0) rev::shader::SetInt(mesh_shader, loc_tex, 0);
                        if (loc_has_tex >= 0) rev::shader::SetInt(mesh_shader, loc_has_tex, 1);
                    } else {
                        if (loc_has_tex >= 0) rev::shader::SetInt(mesh_shader, loc_has_tex, 0);
                    }
                    
                    rev::mesh::Render(mesh_obj, -1);
                }
            }

            if (blend_on) glDisable(GL_BLEND);
            if (depth_on) glDisable(0x0B71); // GL_DEPTH_TEST
        }

        // Swap buffers
        rev::platform::SwapBuffers(window);
        
        // Exit after total duration or on ESC
        if (time > total_duration || rev::platform::IsKeyPressed(window, VK_ESCAPE)) {
            break;
        }
    }
    
    // Cleanup audio
    if (audio_state) {
        audio_state->stop = true;
        if (audio_thread) {
            WaitForSingleObject(audio_thread, 2000);
            CloseHandle(audio_thread);
        }
        waveOutClose(audio_state->wave_out);
        delete audio_state;
    }
    if (xm_player) {
        rev::xm::DestroyPlayer(xm_player);
    }
    if (sprite_shader) {
        rev::shader::DestroyProgram(sprite_shader);
    }
    if (mesh_shader) {
        rev::shader::DestroyProgram(mesh_shader);
    }
    if (mesh_obj) {
        rev::mesh::DestroyMesh(mesh_obj);
    }
    rev::shader::DestroyProgram(shader);
    rev::platform::DestroyIntroWindow(window);
    
    // Clean up curves
    for (int i = 0; i < curve_count; ++i) {
        rev::curve::DestroyCurve(curves[i]);
    }
    
    Gdiplus::GdiplusShutdown(gdiplusToken);
    
    if (g_logfile) {
        fflush(g_logfile);
        fclose(g_logfile);
    }
    
    return 0;
}

